# Page settings
baseurl = "https://libreweb.org"
title = "LibreWeb: üåç Decentralized Internet"
languageCode = "en"
theme = "libreweb"
disableHugoGeneratorInject = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]  
  #custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Melroy van den Berg"
  description = "LibreWeb Browser - Decentralized Internet alternative, using IPFS."
  keywords = "LibreWeb, browser, decentralized, IPFS, content, markdown, web, world wide web, WWW, publish, docs"
  email = ""

  # Navigation
  [params.navigation]
    brand = "LibreWeb"
    home = "Home"
    features = "Features"
    about = "About"
    help = "Help"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://docs.libreweb.org"
      name = "Docs"
      weight = 10

    [[menu.postpend]]
      url = "https://gitlab.melroy.org/libreweb/browser/-/releases"
      name = "Download"
      weight = 10
  
  # Hero section
  [params.hero]
    title = "LibreWeb Browser"
    subtitle = 'Decentralized Web Browser built on top of <a href="https://ipfs.io/" target="_blank">IPFS</a>'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  #[[params.intro.item]]
  #  title = "Plan"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Get In Touch"
  #  icon = "icon-bulb"
  #  img = "img_7.jpg"

  #[[params.intro.item]]
  #  title = "Develop"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Click Me"
  #  icon = "icon-wrench"
  #  img = "img_8.jpg"

  #[[params.intro.item]]
  #  title = "Launch"
  #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #  url = "#"
  #  button = "Why us?"
  #  icon = "icon-rocket"
  #  img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "fa-play-circle"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # features section
  [params.features]
    enable = true
    title = "Main Features"
    description = "Why should you choose LibreWeb?"

    # Feature list
    [[params.features.item]]
      title = "Decentralized"
      description = 'The <a target="_blank" href="https://ipfs.io/">InterPlanetary File System (IPFS)</a> protocol ensures that content is distributed across nodes and delivered reliably with no potential single-point-of-failure. LibreWeb capitalizes on all the benefits of IPFS and then some.'
      icon = "fa-hubzilla"

    [[params.features.item]]
      title = "No Censorship"
      description = "Neither governments nor corporations can censor or block content due LibreWeb's decentralized nature."
      icon = "fa-eye-slash"

    [[params.features.item]]
      title = "Fast & Easy"
      description = "LibreWeb Browser renders content fast, using easy Markdown syntax as source-code. <b>Anyone</b> can easily build a website <b>without</b> <b><i>any</i></b> technical skills using LibreWeb's built-in, familiar, user-friendly content editor and Markdown. With LibreWeb Browser, content is King."
      icon = "fa-clock-o"

    [[params.features.item]]
      title = "Open-Source"
      description = "LibreWeb Browser is fully open-source, <b>free software</b> licensed under the MIT license."
      icon = "fa-microphone"

    [[params.features.item]]
      title = "Secure"
      description = "Data is content-addressed and searchable via your public key (signed by your private key)."
      icon = "fa-shield"

    [[params.features.item]]
      title = "Anonymous"
      description = "Surf anonymously on the decentralized web, the way the WWW was intended. There's no javascript, no tracking, no cookies, no telemetry, no adware."
      icon = "fa-question"

  # About section
  [params.about]
    enable = true
    title = "About"
    contributors = "Contributors"
    description = 'Todays Internet is centralized and controlled by big (tech) businesses and corporations. Even governments have controls over the Internet. With LibreWeb that will change.<br/><br/>The goal of LibreWeb is to have a fully-free & open-source, decentralized Internet - with <b>no</b> potential single-point-of-failure and <b>no</b> censorship.<br/><br/><a href="https://docs.libreweb.org/concepts/" target="_blank">Read the basic concepts <i class="fa fa-external-link" style="font-size: 1.2rem; vertical-align: middle" aria-hidden="true"></i></a>'

    [[params.about.item]]
      name = "Melroy van den Berg"
      position = "Creator/Founder"
      description = "I became inspired to create a decentralized web.\n\nLibreWeb Browser effectively counters a world that is becoming increasingly centralized, monetized and censored by big-tech corporations and governments."
      img = "melroy.jpg"
      alt = "Melroy van den Berg"
      social = [
        ["fa-matrix-org", "https://matrix.to/#/#libreweb:melroy.org?via=melroy.org"],
        ["fa-twitter", "https://twitter.com/LibreWebOrg"],
        ["fa-facebook", "https://www.facebook.com/LibreWeb.org"],
        ["fa-gitlab", "https://gitlab.melroy.org/libreweb/browser"]
      ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "fa-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "fa-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "fa-coffee"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "fa-users"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Help section
  [params.help]
    enable = true
    title = "Getting help"
    description = "If you are looking for help or support,<br/>here is a list to get you started:"

    [[params.help.items]]
      content = '<b>Documentation:</b> Find out more about the LibreWeb project, answers to your FAQs, How-Tos and ways to connect with the LibreWeb community at the <a href="https://docs.libreweb.org" target="_blank">LibreWeb Documentation</a> web site.'
    #[[params.help.items]]
    #  content = '<b>Technical support:</b> Reach out to our official LibreWeb forums.'
    [[params.help.items]]
      content = '<b>General Questions & Discussions:</b> Use <a href="https://matrix.to/#/#libreweb:melroy.org?via=melroy.org" target="_blank">Matrix</a> or <a href="https://t.me/libreweb" target="_blank">Telegram</a>.'
    [[params.help.items]]
      content = '<b>Bugs & Feature Requests:</b> <a href="https://gitlab.melroy.org/libreweb/browser/-/issues" target="_blank">Submit an issue</a> on the LibreWeb Browser GitLab repository.'
    [[params.help.items]]
      content = '<b>Contribute:</b> Do you like to contribute? There are several different ways you can speed up the coming of a truly free and decentralized Internet! Check out the <a href="https://docs.libreweb.org/project/contribute/" target="_blank">Contribute</a> page to find out more.'

  # Contact section
  [params.contact]
    enable = true
    form = true
    title = "Get in touch"
    description = 'Join us on <a href="https://t.me/libreweb" target="_blank">Telegram</a> or <a href="https://matrix.to/#/#libreweb:melroy.org?via=melroy.org" target="_blank">Matrix</a>. Send an <a id="mailto">e-mail</a>, or just fill out the contact form below.'
 
    name = "Your name"
    email = "your@mail.com"
    subject = "Subject"
    message = "Message"
    button = "Send message"
    
    successful = "Thank you! Your message has been sent. We will contact you as soon as possible if needed."
    error = "Something went wrong during the submission of your message."

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; LibreWeb, developed by Melroy van den Berg, content licensed by <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank"><i class="fa fa-cc" aria-hidden="true"></i>&nbsp;3.0</a>.'
    social = [
        ["fa-gitlab", "https://gitlab.melroy.org/libreweb/browser"],
        ["fa-github", "https://github.com/LibreWeb/Browser"],
        ["fa-telegram", "https://t.me/libreweb"],
        ["fa-matrix-org", "https://matrix.to/#/#libreweb:melroy.org?via=melroy.org"],
        ["fa-twitter", "https://twitter.com/LibreWebOrg"],
        ["fa-facebook", "https://www.facebook.com/LibreWeb.org"],
        ["fa-linkedin", "https://www.linkedin.com/company/libreweb"],
        ["fa-reddit", "https://www.reddit.com/r/libreweb"],
        ["fa-youtube", "https://www.youtube.com/channel/UC1wZpYca2iu4pJ3bhZ3azcw"]
      ]

    # Links in footer
    [[params.footer.links]]
      url = "https://gitlab.melroy.org/libreweb/browser/-/releases"
      name = "Download"

    [[params.footer.links]]
      url = "https://docs.libreweb.org"
      name = "Docs"

    [[params.footer.links]]
      url = "https://gitlab.melroy.org/libreweb/browser"
      name = "GitLab"

    [[params.footer.info_links]]
      url = "https://docs.libreweb.org/community"
      name = "Community"

    [[params.footer.info_links]]
      url = "https://docs.libreweb.org/faq"
      name = "FAQ"

    [[params.footer.info_links]]
      url = "https://docs.libreweb.org/project/contribute/"
      name = "Contribute"

# Blog still todo
#    [[params.footer.info_links]]
#      url = "https://blog.libreweb.org"
#      name = "Blog"

    [[params.footer.info_links]]
      url = "#fh5co-contact"
      name = "Contact"

ignoreFiles = [
    "themes/libreweb/README.md",
    "themes/libreweb/LICENSE.md"
]
